<Project>
    <PropertyGroup>
        <TargetFramework>net472</TargetFramework>
        <OutputType>library</OutputType>
        <LangVersion>default</LangVersion>
        <Authors>Rohan Vazarkar</Authors>
        <Company>SpecterOps</Company>
        <PackageLicenseExpression>GPL-3.0-only</PackageLicenseExpression>
        <RepositoryUrl>https://github.com/SpecterOps/SharpHoundCommon</RepositoryUrl>
        <Version>4.8.0</Version>
    </PropertyGroup>
    <ItemGroup>
        <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
            <_Parameter1>CommonLibTest</_Parameter1>
        </AssemblyAttribute>
    </ItemGroup>
</Project>
